### ISSUE TITLE
Figure out coalesce

### ISSUE THREAD

**Issue by apendleton** [mapbox/carmen-core#2]
#1 proposes writing a new grid storage backend. In addition to the backend and basic IO, we'll need to be able to run `coalesce` operations against it. Two options:

## C++ coalesce
The `carmen-cache-sys` subdirectory has the beginnings (totally untested) of how we might wrap the existing coalesce logic from carmen-cache into this library. We could continue to pursue this direction. I started attempting to wrap the entirety of the existing backends, but ultimately I think this is probably a waste of time, and was looking like it would likely be very challenging to complete. Instead, we should cut a branch of carmen-cache that removes all the stuff we no longer care about, and modifies `coalesce` to be more palatable to being wrapped.

In particular:
- [ ] don't depend on rocksdb anymore at all, to make linking easier; the Rust side will own that now
- [ ] stop communicating via hard-to-instantiate STL types, in favor, of simpler structs that can be created from either side and easily copied back and forth (no more `std::pair` or `std::tuple`, and probably no more `std::vector` or `std::string` either, in favor of new C++ slices and spans)
- [ ] stop having coalesce try to cast the cache into one of its internal types. Maybe instead we should pass in a function pointer that retrieves the data coalesce needs in a Rust-y way and just returns back a buffer, or something like that
- [ ] stop expecting data back as packed ints -- it should get back data as a buffer of structs

## Rust coalesce
Alternatively, we could just port it. It's like 300 lines. Increasingly I'm feeling like that's the best bet.

**Comment by Nmargolis** [comment]
We ported it in #20
