### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by apendleton** [mapbox/carmen-core#3]
We should build out the machinery for Rust-side unit tests and benchmarks (the latter probably using `criterion`).

**Comment by miccolis** [comment]
Capturing some discussion from chat w. @apendleton about benchmarks;

> The other option, though, would be to try and come up with a strategy for benching that actually at least sort of reflects production... on the fuzzy phrase side we have production-sized phrase dictionaries derived from open data sources, so maybe it's worth doing something like that... or, alternatively, building a benching tool that depends on private data, and then assembling a private corpus from our existing data sources
> In the past when benching coalesce and wanting to pass around a self-contained thing, I've used the `gb-*` indexes, which are big enough to be nontrivially but not so big that they can't be downloaded fairly quickly
> so if we went that route, we could maybe extract all the grids from current carmen cache into some easier-to-read format, put them on s3, and build some infrastructure to, during a bench run, download that data and index it, and run a bunch of real coalesces against it -- last time, I captured a bunch of actual coalesce calls from gb test runs

**Comment by Nmargolis** [comment]
Added in #36, next steps outlined in #39
