### ISSUE TITLE
JS wrapper

### ISSUE THREAD

**Issue by apendleton** [mapbox/carmen-core#5]
We should create a Node wrapper using `neon`, with `neon-serde` for data interop. We should then write JS-side tests, possibly porting tests from existing carmen-cache

**Comment by aarthykc** [comment]
After https://github.com/mapbox/carmen-core/pull/8 lands, next actions look like: 
- [ ] Write js wrappers for the writer and the reader functions
- [ ] Write tests that can be run by `npm test`
- [ ] Provide the ability to publish binaries
