### ISSUE TITLE
Figure out what to do with frequency stuff

### ISSUE THREAD

**Issue by apendleton** [mapbox/carmen-core#6]
Right now in carmen we use carmen-cache, hackily, to store frequency data as well as grid data -- essentially using it as a basic key-value store and taking advantage of the fact that it uses integers as input and output, even though in most contexts carmen-cache assumes that those integers actually contain structured data, and they don't in this circumstance. Now that we're changing the API to be explicitly structured rather than using integers for interop, this won't fly anymore, so we'll need to figure out a different place to put this stuff (maybe via a differing interface exposed by this library over rocksdb, or maybe just some other simpler storage accessible directly from the carmen side).

**Comment by miccolis** [comment]
Plan is to tear out the frequency store, we only use the max score value in this table at query time anyhow. See https://github.com/mapbox/carmen/issues/853
